---
stages:
- name: Build
  inputs:
  - service: ${APP_REPO}
    type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    extension_id: ibm.devops.services.pipeline.npm.build
    SERVICE_INSTANCE: (default)
    BUILD_COMMAND: |-
      #!/bin/bash
      # environment variables are available:
      # NPM_NAME: name of the service instance
      # NPM_USER_ID: userid for the npm registry
      # NPM_TOKEN: the token or password for the npm registry
      # NPM_RELEASE_URL: the private NPM registry
      # NPM_MIRROR_URL: the proxy NPM registry, used as the default NPM registry
      # NPM_MODULE_NAME: the module name of the package.json at the root of the workspace if available.

      npm install
      #npm publish --registry "${NPM_RELEASE_URL}"
      #npm install "${NPM_MODULE_NAME}"
    SERVICE_INSTANCE_TYPE: nexus
- name: Test
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Unit tests
    type: tester
    script: |-
      #!/bin/bash

      #npm test
- name: Deploy [Dev]
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash

      cf push "${CF_APP}" --hostname "${CF_APP}" -m 64M -p .
- name: System Test [DEV]
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Test
    type: tester
    script: |-
      #!/bin/bash

      #curl something here
- name: Publish to Nexus
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Publish
    type: builder
    extension_id: ibm.devops.services.pipeline.npm.build
    INC_SNAPSHOT: 'true'
    SERVICE_INSTANCE: (default)
    BUILD_COMMAND: |
      #!/bin/bash
      # environment variables are available:
      # NPM_NAME: name of the service instance
      # NPM_USER_ID: userid for the npm registry
      # NPM_TOKEN: the token or password for the npm registry
      # NPM_RELEASE_URL: the private NPM registry
      # NPM_MIRROR_URL: the proxy NPM registry, used as the default NPM registry
      # NPM_MODULE_NAME: the module name of the package.json at the root of the workspace if available.


      npm publish --registry "${NPM_RELEASE_URL}"
    SERVICE_INSTANCE_TYPE: nexus
