---
stages:
- name: Build
  inputs:
  - service: ${ECHO_REPO}
    type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    extension_id: ibm.devops.services.pipeline.npm.build
    SERVICE_INSTANCE: (default)
    BUILD_COMMAND: |
      #!/bin/bash
      # environment variables are available:
      # NPM_NAME: name of the service instance
      # NPM_USER_ID: userid for the npm registry
      # NPM_TOKEN: the token or password for the npm registry
      # NPM_RELEASE_URL: the private NPM registry
      # NPM_MIRROR_URL: the proxy NPM registry, used as the default NPM registry
      # NPM_MODULE_NAME: the module name of the package.json at the root of the workspace if available.

      npm install
    SERVICE_INSTANCE_TYPE: nexus
- name: Test
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Unit test
    type: tester
    script: |-
      #!/bin/bash

      #npm test
- name: Publish to Nexus
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Publish
    type: builder
    extension_id: ibm.devops.services.pipeline.npm.build
    INC_SNAPSHOT: 'true'
    SERVICE_INSTANCE: (default)
    BUILD_COMMAND: |
      #!/bin/bash
      # environment variables are available:
      # NPM_NAME: name of the service instance
      # NPM_USER_ID: userid for the npm registry
      # NPM_TOKEN: the token or password for the npm registry
      # NPM_RELEASE_URL: the private NPM registry
      # NPM_MIRROR_URL: the proxy NPM registry, used as the default NPM registry
      # NPM_MODULE_NAME: the module name of the package.json at the root of the workspace if available.


      npm publish --registry "${NPM_RELEASE_URL}"
    SERVICE_INSTANCE_TYPE: nexus
